# -*- coding: utf-8 -*-
"""Gender Predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OW84zVrc1NJ56dKlft7iQmGYN_M2VDOx

# ML Project : Predicting Gender
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Step 1: Import necessary libraries"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

"""### Step 2: Load and read the Dataset"""

DataSet = pd.read_csv('/content/drive/MyDrive/Machine Learning/Datasets/gender_classification_v7.csv')
DataSet.head()
print('Shape of our dataset: {}'.format(DataSet.shape))

"""### Step 3: Check and remove all the null values"""

DataSet.isnull().sum()

"""#### N.B: If there were null values, then we would have imputed the data using simpleImputer

### Step 4: One-Hot encoding
"""

DataSet['gender'].unique()
encoder = LabelEncoder()
DataSet['gender'] = encoder.fit_transform(DataSet['gender'])
DataSet.head()

"""### Step 5: Split the data"""

x_train, x_test, y_train, y_test = train_test_split(DataSet, DataSet.gender, test_size=0.2, random_state=0)
print('x_train shape: {}'.format(x_train.shape))
print('x_test shape: {}'.format(x_test.shape))
print('y_train shape: {}'.format(y_train.shape))
print('y_test shape: {}'.format(y_test.shape))

"""### Step 6: Scale the data"""

scaler = MinMaxScaler()

scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
scaler.fit(x_test)
x_test_scaled = scaler.transform(x_test)

"""### Step 7: Train the model"""

model = LogisticRegression()
model.fit(x_train_scaled, y_train)

"""### Step 8: Test the model"""

predictions = model.predict(x_test_scaled)
print('Prediction: ',pd.DataFrame(predictions).head())
print('Actual: ',pd.DataFrame(y_test).head())